//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookLog
    {
        public int Book_event_id { get; set; }
        public Nullable<int> Serial_item_id { get; set; }
        public Nullable<int> Location_id { get; set; }
        public string Action { get; set; }
        public string Time_stamp { get; set; }
        public string Title { get; set; }
        public string Isbn { get; set; }
        public Nullable<int> Item_id { get; set; }
    }
}
