//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        public int Fine_id { get; set; }
        public int Member_id { get; set; }
        public string Status { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Deadline { get; set; }
        public Nullable<int> Serial_item_id { get; set; }
        public string Reason { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual SerialItem SerialItem { get; set; }
    }
}
