//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberCard
    {
        public string Member_card_id { get; set; }
        public int Member_id { get; set; }
        public System.DateTime Expired_date { get; set; }
        public System.DateTime Create_date { get; set; }
        public byte[] Photo { get; set; }
    }
}
