//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberCampusAddress
    {
        public int Member_id { get; set; }
        public string Campus_Address { get; set; }
    
        public virtual NormalMember NormalMember { get; set; }
    }
}
