//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormalMember
    {
        public int Member_id { get; set; }
        public string Ssn { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public int Member_type { get; set; }
        public Nullable<int> Loan_rule_id { get; set; }
        public int User_id { get; set; }
        public string Gender { get; set; }
    
        public virtual Loan_Rule Loan_Rule { get; set; }
        public virtual Member Member { get; set; }
        public virtual MemberCampusAddress MemberCampusAddress { get; set; }
        public virtual User User { get; set; }
    }
}
