//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormalMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NormalMember()
        {
            this.MemberCards = new HashSet<MemberCard>();
        }
    
        public int Member_id { get; set; }
        public string Ssn { get; set; }
        public int Member_type { get; set; }
        public int User_id { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual MemberCampusAddress MemberCampusAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberCard> MemberCards { get; set; }
        public virtual User User { get; set; }
    }
}
