//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Reservation_id { get; set; }
        public int Member_id { get; set; }
        public System.DateTime Reserve_time { get; set; }
        public Nullable<System.DateTime> Expected_return_date { get; set; }
        public Nullable<System.DateTime> Checkout_time { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<System.DateTime> Returned_time { get; set; }
        public Nullable<short> Pickup_method { get; set; }
        public int Batch_id { get; set; }
    
        public virtual InsideReservation InsideReservation { get; set; }
        public virtual Member Member { get; set; }
        public virtual OutsideReservation OutsideReservation { get; set; }
    }
}
