//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp.DataAccess
{
    
    public partial class Book
    {
        public int book_no { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string review { get; set; }
        public string isbn { get; set; }
    }
}
