F
=C:\Code\Prototype\BookApp\BookApp.Tests\BookControllerTest.csutf-8K
BC:\Code\Prototype\BookApp\BookApp.Tests\Properties\AssemblyInfo.csutf-8€
pC:\Code\Prototype\BookApp\BookApp.Tests\obj\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cswindows-1252€
pC:\Code\Prototype\BookApp\BookApp.Tests\obj\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cswindows-1252€
pC:\Code\Prototype\BookApp\BookApp.Tests\obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cswindows-1252‚
rC:\Code\Prototype\BookApp\BookApp.Tests\obj\Release\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cswindows-1252‚
rC:\Code\Prototype\BookApp\BookApp.Tests\obj\Release\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cswindows-1252‚
rC:\Code\Prototype\BookApp\BookApp.Tests\obj\Release\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cswindows-1252L
<C:\Code\Prototype\BookApp\BookApp\App_Start\SwaggerConfig.cswindows-1252J
:C:\Code\Prototype\BookApp\BookApp\App_Start\UnityConfig.cswindows-1252S
CC:\Code\Prototype\BookApp\BookApp\App_Start\UnityWebApiActivator.cswindows-1252D
;C:\Code\Prototype\BookApp\BookApp\App_Start\WebApiConfig.csutf-8I
@C:\Code\Prototype\BookApp\BookApp\Controllers\BooksController.csutf-8H
?C:\Code\Prototype\BookApp\BookApp\Controllers\ItemController.csutf-8H
?C:\Code\Prototype\BookApp\BookApp\Controllers\LoanController.csutf-8J
AC:\Code\Prototype\BookApp\BookApp\Controllers\MemberController.csutf-8P
GC:\Code\Prototype\BookApp\BookApp\Controllers\NormalMemberController.csutf-8N
EC:\Code\Prototype\BookApp\BookApp\Controllers\PermissionController.csutf-8M
DC:\Code\Prototype\BookApp\BookApp\Controllers\UserGroupController.csutf-8I
@C:\Code\Prototype\BookApp\BookApp\Controllers\UsersController.csutf-8W
NC:\Code\Prototype\BookApp\BookApp\CustomException\BookNotAvailableException.csutf-8V
MC:\Code\Prototype\BookApp\BookApp\CustomException\ExceedLoanLimitException.csutf-8U
LC:\Code\Prototype\BookApp\BookApp\CustomException\MemberNotFoundException.csutf-8R
IC:\Code\Prototype\BookApp\BookApp\DataAccess\Interface\IBookRepository.csutf-8K
BC:\Code\Prototype\BookApp\BookApp\DataAccess\Interface\IContext.csutf-8R
IC:\Code\Prototype\BookApp\BookApp\DataAccess\Interface\IItemRepository.csutf-8X
OC:\Code\Prototype\BookApp\BookApp\DataAccess\Interface\IItemStatusRepository.csutf-8T
KC:\Code\Prototype\BookApp\BookApp\DataAccess\Interface\IMemberRepository.csutf-8Z
QC:\Code\Prototype\BookApp\BookApp\DataAccess\Interface\INormalMemberRepository.csutf-8X
OC:\Code\Prototype\BookApp\BookApp\DataAccess\Interface\IPermissionRepository.csutf-8N
EC:\Code\Prototype\BookApp\BookApp\DataAccess\Interface\IRepository.csutf-8Y
PC:\Code\Prototype\BookApp\BookApp\DataAccess\Interface\IReservationRepository.csutf-8X
OC:\Code\Prototype\BookApp\BookApp\DataAccess\Interface\ISerialItemRepository.csutf-8W
NC:\Code\Prototype\BookApp\BookApp\DataAccess\Interface\IUserGroupRepository.csutf-8R
IC:\Code\Prototype\BookApp\BookApp\DataAccess\Interface\IUserRepository.csutf-8R
IC:\Code\Prototype\BookApp\BookApp\DataAccess\Repository\BookRepository.csutf-8O
FC:\Code\Prototype\BookApp\BookApp\DataAccess\Repository\DataContext.csutf-8R
IC:\Code\Prototype\BookApp\BookApp\DataAccess\Repository\ItemRepository.csutf-8X
OC:\Code\Prototype\BookApp\BookApp\DataAccess\Repository\ItemStatusRepository.csutf-8T
KC:\Code\Prototype\BookApp\BookApp\DataAccess\Repository\MemberRepository.csutf-8Z
QC:\Code\Prototype\BookApp\BookApp\DataAccess\Repository\NormalMemberRepository.csutf-8X
OC:\Code\Prototype\BookApp\BookApp\DataAccess\Repository\PermissionRepository.csutf-8N
EC:\Code\Prototype\BookApp\BookApp\DataAccess\Repository\Repository.csutf-8Y
PC:\Code\Prototype\BookApp\BookApp\DataAccess\Repository\ReservationRepository.csutf-8X
OC:\Code\Prototype\BookApp\BookApp\DataAccess\Repository\SerialItemRepository.csutf-8N
EC:\Code\Prototype\BookApp\BookApp\DataAccess\Repository\UnitOfWork.csutf-8W
NC:\Code\Prototype\BookApp\BookApp\DataAccess\Repository\UserGroupRepository.csutf-8R
IC:\Code\Prototype\BookApp\BookApp\DataAccess\Repository\UserRepository.csutf-89
0C:\Code\Prototype\BookApp\BookApp\Global.asax.csutf-8E
<C:\Code\Prototype\BookApp\BookApp\Properties\AssemblyInfo.csutf-8M
DC:\Code\Prototype\BookApp\BookClient.Tests\Controllers\LoginTests.csutf-8L
CC:\Code\Prototype\BookApp\BookClient.Tests\Model\MockHttpSession.csutf-8N
EC:\Code\Prototype\BookApp\BookClient.Tests\Properties\AssemblyInfo.csutf-8ƒ
sC:\Code\Prototype\BookApp\BookClient.Tests\obj\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cswindows-1252ƒ
sC:\Code\Prototype\BookApp\BookClient.Tests\obj\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cswindows-1252ƒ
sC:\Code\Prototype\BookApp\BookClient.Tests\obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cswindows-1252…
uC:\Code\Prototype\BookApp\BookClient.Tests\obj\Release\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cswindows-1252…
uC:\Code\Prototype\BookApp\BookClient.Tests\obj\Release\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cswindows-1252…
uC:\Code\Prototype\BookApp\BookClient.Tests\obj\Release\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cswindows-1252G
>C:\Code\Prototype\BookApp\BookClient\App_Start\BundleConfig.csutf-8F
=C:\Code\Prototype\BookApp\BookClient\App_Start\RouteConfig.csutf-8M
=C:\Code\Prototype\BookApp\BookClient\App_Start\UnityConfig.cswindows-1252S
CC:\Code\Prototype\BookApp\BookClient\App_Start\UnityMvcActivator.cswindows-1252G
>C:\Code\Prototype\BookApp\BookClient\Controllers\BookAppUri.csutf-8K
BC:\Code\Prototype\BookApp\BookClient\Controllers\BookController.csutf-8K
BC:\Code\Prototype\BookApp\BookClient\Controllers\HomeController.csutf-8L
CC:\Code\Prototype\BookApp\BookClient\Controllers\LoginController.csutf-8O
FC:\Code\Prototype\BookApp\BookClient\Controllers\RegisterController.csutf-8J
AC:\Code\Prototype\BookApp\BookClient\Enum\EmployeePositionEnum.csutf-8D
;C:\Code\Prototype\BookApp\BookClient\Enum\MailChoiceEnum.csutf-8D
;C:\Code\Prototype\BookApp\BookClient\Enum\MemberTypeEnum.csutf-8D
;C:\Code\Prototype\BookApp\BookClient\Enum\PermissionEnum.csutf-8G
>C:\Code\Prototype\BookApp\BookClient\Factory\ServiceFactory.csutf-8<
3C:\Code\Prototype\BookApp\BookClient\Global.asax.csutf-8J
AC:\Code\Prototype\BookApp\BookClient\Interface\IServiceFactory.csutf-8H
?C:\Code\Prototype\BookApp\BookClient\Properties\AssemblyInfo.csutf-8O
FC:\Code\Prototype\BookApp\BookClient\ViewModels\CreateBookViewModel.csutf-8O
FC:\Code\Prototype\BookApp\BookClient\ViewModels\SearchBookViewModel.csutf-8P
GC:\Code\Prototype\BookApp\BookClient\ViewModels\UserAccountViewModel.csutf-8N
EC:\Code\Prototype\BookApp\BookClient\ViewModels\UserLoginViewModel.csutf-8