//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int User_id { get; set; }
        public string Work_phone { get; set; }
        public short Position { get; set; }
    
        public virtual User User { get; set; }
    }
}
