//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemStatu
    {
        public int Item_id { get; set; }
        public short Total_copy { get; set; }
        public Nullable<int> Location_id { get; set; }
        public Nullable<short> Reserved_copy { get; set; }
        public Nullable<short> Missing_copy { get; set; }
        public Nullable<short> Damaged_copy { get; set; }
        public Nullable<short> Checkout_copy { get; set; }
        public bool Can_loan_out { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Location Location { get; set; }
    }
}
