//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.NormalMembers = new HashSet<NormalMember>();
        }
    
        public string User_name { get; set; }
        public int User_id { get; set; }
        public string Password { get; set; }
        public System.DateTime Create_time { get; set; }
        public short User_group_id { get; set; }
        public string FIrst_name { get; set; }
        public string Last_name { get; set; }
        public bool Is_Female { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NormalMember> NormalMembers { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
